# Generated by Django 5.0.4 on 2024-11-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delimiter_data',
            field=models.CharField(default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='source',
            name='delimiter_place',
            field=models.CharField(default=',', max_length=1),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
