# Generated by Django 5.0.4 on 2024-11-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_source_delimiter_data_source_delimiter_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='hasSoil',
        ),
        migrations.RemoveField(
            model_name='site',
            name='hasTemporal',
        ),
        migrations.RemoveField(
            model_name='source',
            name='delimiter_data',
        ),
        migrations.RemoveField(
            model_name='source',
            name='delimiter_place',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url_data',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url_place',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='hasSoil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='hasTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standard',
            name='summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.URLField(max_length=255)),
                ('delimiter', models.CharField(default=',', max_length=1)),
                ('isSoil', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.source')),
            ],
        ),
        migrations.AddField(
            model_name='synonym',
            name='dataset',
            field=models.ManyToManyField(to='base.dataset'),
        ),
    ]
